.TH DEF2FGD 1
.SH НАЗВАНИЕ
def2fgd \- переводит .def и .ent в .fgd
.SH СИНТАКСИС
.B def2fgd
.I [OPTIONS...]
.I [INPUTE-FILE]
.I [OUTPUT-FILE]
.SH ОПИСАНИЕ
.B def2fgd
переводит .def and .ent файлы, используемые
в GtkRadiant и NetRadiant, в .fgd
файлы, используемые в Jackhammer.
.SH ПАРАМЕТРЫ
.TP
\fB\-format формат\fP
Указывает формат входных данных. Возможные значения: def и ent.
По умолчанию формат определяется по расширению входного файла.

.TP
\fB\-offset-glob шаблон\fP
Добавить дополнительный шаблон для поиска энтить, которым нужен сдвиг.
Укажите эту опцию несколько раз для добавления нескольких шаблонов.
.br
Сдвиг используется в редакторе карт при создании точечных энтить в 3D-виде.
.br
Шаблоны по умолчанию: weapon_*, item_*, ammo_*, info_player_deathmatch и info_player_start.

.TP
\fB-noauto-offset-glob\fP
Не использовать шаблоны по умолчанию для установки сдвига, оставить только явно добавленные.

.TP
\fB-bobparms "x y z"\fP
Установить параметры вращения для всех вращающихся энтитей. Все три параметры должны быть посланы как один аргумент, т.е. в кавычках.
.br
Если вы не знаете, как задаются параметры вращения, но хотите, чтобы модели оружия и предметов парили и вращались, используйте опцию -bob.

.TP
\fB\-bob\fP
То же самое, что -bobparms "180 8 0".
При таком значении модели предметов парят и вращаются в 3D-виде редактора карт так же, как в Quake III Arena и других похожих играх.

.TP
\fB\-bob-glob шаблон\fP
Добавить дополнительный шаблон для поиска энтить, которым нужны параметры вращения.
Укажите эту опцию несколько раз для добавления нескольких шаблонов.

Шаблоны по умолчанию: weapon_*, item_* и ammo_*.

.TP
\fB-noauto-bob-glob\fP
Не использовать шаблоны по умолчанию для установки параметров вращения, оставить только явно добавленные.

.TP
\fB\-help\fP
Показать справку и выйти.

.TP
\fB\-version\fP
Показать версию и выйти.

.TP
\fB\-\-\ [arguments...]\fP
Считать оставшуюся часть аргументов позиционными аргументами (т.е. не опциями).

Когда INPUTE-FILE не задан или равняется -, используется стандартный поток ввода.

Когда OUTPUT-FILE не задан или OUTPUT-FILE is -, используется стандартный поток вывода.

.SH ПРИМЕРЫ

.TP
def2fgd entities.def entities.fgd
Прочитать entitites.def и записать результат в entities.fgd.

.TP
def2fgd -format def - entities.fgd < entities.def
Читать ищ стандартного потока ввода и записать результат в entities.fgd.
При чтении из стандартного потока ввода формат входных даных должен быть указан явно.

.TP
def2fgd entities.def > entities.fgd
Прочитать entities.def и вывести результат в стандартный поток вывода.

.TP
def2fgd -bob entities.def entities.fgd
Добавить параметры вращения по умолчанию для оружия, предметов и боеприпасов.

.TP
def2fgd -bobparms "100 0 0" entities.def entities.fgd
Назначить собственные параметры вращения оружия, предметов и боеприпасов.

.TP
def2fgd -noauto-offset-glob -offset-glob item_* -offset-glob weapon_* entities.def entities.fgd
Добавить сдвиг только для энтить, чьи имена начинаются с item_ и weapon_

.TP
def2fgd -bob -bob-glob key_* -offset-glob key_* entities.def entities.fgd
Добавить сдвиг и параметры вращения для энтитей, названия которых начинаются с key_, а также для тех, что соответствуют шаблонам по умолчанию.

.SH АВТОР
Roman Chistokhodov https://bitbucket.org/FreeSlave/
