.TH DEF2FGD 1
.SH NAME
def2fgd \- convert .def and .ent to .fgd
.SH SYNOPSIS
.B def2fgd
.I [OPTIONS...]
.I [INPUTE-FILE]
.I [OUTPUT-FILE]
.SH DESCRIPTION
.B def2fgd
converts GtkRadiant and NetRadiant .def 
and .ent files to Jackhammer .fgd.
.SH OPTIONS
.TP
\fB\-format format\fP
Specify format of input. Valid values are def and ent. 
By default format is detected from input file extension.

.TP
\fB\-offset-glob pattern\fP
Add an extra pattern for matching entity names that needs offset.

Offset will be used in level editor when creating point entities in 3D view.

Default patterns are weapon_*, item_*, ammo_*, info_player_deathmatch and info_player_start.

.TP
\fB-noauto-offset-glob\fP
Don't use default patterns when setting offset, only explicitly added ones.

.TP
\fB-bobparms "x y z"\fP
Set bob parameters for all bobbing entitites. Note that all three parameters should be passed as single argument, i.e. in pair quotes.

If you don't know what bob parameters mean, but still want specific models (like weapons and items) to float and rotate, use just -bob.

.TP
\fB\-bob\fP
Same as -bobparms "180 8 0". 

This is good default since it makes models to float and rotate in 3D view of level editor the same way as they do in Quake III Arena and similar games.

.TP
\fB\-bob-glob pattern\fP
Add an extra pattern for matching entity names that needs bobbing parameters.

Default patterns are weapon_*, item_* and ammo_*.

.TP
\fB-noauto-bob-glob\fP
Don't use default patterns when setting bob parameters, only explicitly added ones.

.TP
\fB\-help\fP
Show help message and exit.

.TP
\fB\-version\fP
Show version information and exit.

.TP
\fB\-\-\ [arguments...]\fP
Treat the rest of arguments as positional arguments (i.e. not options).

When no INPUTE-FILE given or INPUTE-FILE is -, standard input is used.

When no OUTPUT-FILE given or OUTPUT-FILE is -, standard output is used.

.SH EXAMPLES

def2fgd entities.def entities.fgd

def2fgd -format def - entities.fgd < entities.def

def2fgd entities.def > entities.fgd

.SH AUTHOR
Roman Chistokhodov https://bitbucket.org/FreeSlave/
