.TH DEF2FGD 1
.SH NAME
def2fgd \- convert .def and .ent to .fgd
.SH SYNOPSIS
.B def2fgd
.I [OPTIONS...]
.I [input-file]
.I [output-file]
.SH DESCRIPTION
.B def2fgd
converts GtkRadiant and NetRadiant .def 
and .ent files to Jackhammer .fgd.
.SH OPTIONS
.TP
\fB\-format format\fP
Specify format of input. Valid values are def and ent. 
By default format is detected from input file extension.

.TP
\fB\-bob\fP
automatically add bobparms for weapons, items and ammo

.TP
\fB\-help\fP
Show help message and exit

.TP
\fB\-version\fP
Show version information and exit

.TP
\fB\-\-\ [arguments...]\fP
Treat the rest of arguments as positional arguments

When no output-file given, standard output is used.

When no input-file given standard input is used.

.SH EXAMPLES

def2fgd entities.def entities.fgd

def2fgd -format def - entities.fgd < entities.def

def2fgd entities.def > entities.fgd

.SH AUTHOR
Roman Chistokhodov https://bitbucket.org/FreeSlave/
