name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cxx: [g++, clang++]
        make: [make]
        include:
          - os: windows-latest
            cxx: g++
            make: mingw64-make
    env:
      CXX: ${{ matrix.cxx }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        ${{ matrix.make }}
